import type { Metadata } from 'next';
import { LegalPage, Section, Fill } from '@/components/legal/legal-page';

export const metadata: Metadata = {
  title: 'Terms of Service — Book Buddy',
  description: 'The terms governing use of the Book Buddy platform.',
};

/** DRAFT — see the notice in the body. Needs review before it is relied upon. */
export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="22 August 2026">
      <p className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-700/50 dark:bg-amber-900/20 dark:text-amber-200">
        <strong>Draft pending legal review.</strong> Complete the highlighted
        values and have this reviewed by a qualified adviser before relying on
        it.
      </p>

      <Section heading="Agreement">
        <p>
          These terms govern your use of Book Buddy, operated by{' '}
          <Fill>[registered entity name]</Fill>. By creating an account you
          accept them. If you are using the platform through an institution,
          your institution&apos;s own agreement may also apply.
        </p>
      </Section>

      <Section heading="Accounts">
        <p>
          You are responsible for keeping your credentials secure and for
          activity under your account. Accounts are personal and may not be
          shared. Repeated failed sign-in attempts temporarily lock an account
          as a security measure. We may suspend an account that is used to
          breach these terms.
        </p>
      </Section>

      <Section heading="Content and licensing">
        <p>
          Books and materials in the shared library are licensed to you for
          personal study for as long as your access lasts. You may not
          redistribute, resell, publish or systematically download them.
          Some titles are watermarked and access-controlled; circumventing those
          protections is a breach of these terms and may infringe the
          rightsholder&apos;s copyright.
        </p>
        <p>
          Files you upload to My Shelf remain yours. You are responsible for
          holding the rights to anything you upload, and you grant us only the
          permission needed to store and display it back to you.
        </p>
      </Section>

      <Section heading="AI features">
        <p>
          Varta, quizzes, recaps and simplified text are generated by language
          models from the book&apos;s own content. They can be wrong. Answers
          carry a citation to the page they came from precisely so you can check
          them, and you should — <strong>do not rely on generated output for
          assessment, medical, legal or safety-critical purposes.</strong>
        </p>
        <p>
          AI features require an active subscription or a free trial. Trial
          usage is capped per feature per day; those limits may change.
        </p>
      </Section>

      <Section heading="Borrowing">
        <p>
          Borrowed titles have a limited loan period and a limited number of
          concurrent copies. <Fill>[State whether overdue fees apply.]</Fill>
        </p>
      </Section>

      <Section heading="Payment and cancellation">
        <p>
          <Fill>
            [Pricing, billing cycle, renewal, refund and cancellation terms.]
          </Fill>
        </p>
      </Section>

      <Section heading="Availability">
        <p>
          We aim to keep the service available but do not guarantee
          uninterrupted access. Maintenance, third-party outages and
          circumstances beyond our control may interrupt it.
        </p>
      </Section>

      <Section heading="Liability">
        <p>
          <Fill>
            [Limitation of liability, to be drafted for your jurisdiction.]
          </Fill>
        </p>
      </Section>

      <Section heading="Governing law">
        <p>
          These terms are governed by the laws of{' '}
          <Fill>[jurisdiction]</Fill>.
        </p>
      </Section>

      <Section heading="Contact">
        <p>
          Questions about these terms: <Fill>[contact email]</Fill>.
        </p>
      </Section>
    </LegalPage>
  );
}
